name: Build and Run

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: ./scripts/build.sh native

    - name: Install
      run: ./scripts/install.sh